### PR TITLE
Add SCSS functions

### PR DESCRIPTION
**Pull request by Matotomax**
- Add deeper map-get: access value of an array in another array. Useful for complex scss array variables.
- Add Color() as first deep-array function

### CODE REVIEW

**Comment by alexandernanberg** [comment]
Can you give some examples of when you need multi-dimensional sass maps? I've not personally found any use-cases.

Unless I'm missing something the new `color` fn won't work with the current `$colors` map?

**Comment by Matotomax** [comment]
You're right, I should have shown an example and also modified the $colors in config too.
I think because of the way we'll handle colors in the future, we need to rethink how we store the color variables.

I'm thinking we should have $colors structure like this instead:
`$colors: (
  gray: (
    100: '#xxx',
    200: '#xxx',
    ...
  ),
  blue: (
    100: '#xxx',
    200:'#xxx',
    ...
);`

Then you can get the colour of your choice by doing `color(blue, 100);`
I personally think it adds more structure to the $colors array and also matches the new style guide template from the designers.

What do you think @jesperjohansson? @mollberg ?

**Comment by jesperjohansson** [comment]
> You're right, I should have shown an example and also modified the $colors in config too.
> I think because of the way we'll handle colors in the future, we need to rethink how we store the color variables.
> 
> I'm thinking we should have $colors structure like this instead:
> `$colors: ( gray: ( 100: '#xxx', 200: '#xxx', ... ), blue: ( 100: '#xxx', 200:'#xxx', ... );`
> 
> Then you can get the colour of your choice by doing `color(blue, 100);`
> I personally think it adds more structure to the $colors array and also matches the new style guide template from the designers.
> 
> What do you think @jesperjohansson? @mollberg ?

I kind of like the way it is now (mostly because I personally don't like the number based way), but I'm not against this if you guys want it

**Comment by Matotomax** [comment]
It's not clear enough if this is the way to go for us at the moment.
I'll keep using this structure for the projects I'm working on where it makes sense.

**Pull request closed without merging**
