### PR TITLE
Normalize.css + cleanup

### PR DESCRIPTION
**Pull request by alexandernanberg**
Some arguments for switching to normalize: 
- https://stackoverflow.com/a/8357635
- http://nicolasgallagher.com/about-normalize-css/

### CODE REVIEW

**Comment by Matotomax** [comment]
Most of it looks good. Again I'm not sure about removing the 10px but I can give it a try I guess.

**Comment by jesperjohansson** [comment]
> Most of it looks good. Again I'm not sure about removing the 10px but I can give it a try I guess.

I feel the same way about the font-size. Whats the purpose though?

**Comment by alexandernanberg** [comment]
Having 10px as the base kinda messes up things if they are totally unstyled. Eg if there is text outside of a `<p />`. Since the designs we'll have to implement will follow the 8pt grid I think it makes sense to have that as the base. However I don't feel too strongly about it and can revert if you want to.

**Comment by Matotomax** [comment]
Yes I agree with what you say… It's quite contradictory to set the html font size to 10px if we're using normalize…

We can give it a try and go back if needed.

**Comment by Matotomax** [comment]
I thought I answered, but yes, I guess we should give it a try without 10px on the html+using normalize

**Pull request merged**
